id = "typedown"
name = "Typedown"
version = "0.1.0"
schema_version = 1
authors = ["Huy Do <huydo862003@example.com>"]
description = "Language server for Typedown - a structured type-safe markdown language"
repository = "https://github.com/huydo862003/typedown"

[grammars.typedown]
repository = "https://github.com/huydo862003/tree-sitter-typedown"
rev = "main"

[language_servers.typedown-lsp]
name = "Typedown LSP"
languages = ["Typedown"]
command = "typedown-lsp"
