id = "typedown"
name = "Typedown"
version = "0.1.0"
schema_version = 1
authors = ["Lucas Nguyen"]
description = "Typedown - a structured type-safe markdown language"
repository = "https://github.com/huydo862003/typedown"

[language_servers.tdr-lsp]
name = "Typedown TDR LSP"
languages = ["TDR"]
command = "tdr-lsp"
