use num_enum::TryFromPrimitive;

/// Stable identifier for a query or input in the dep graph.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, TryFromPrimitive)]
#[repr(u8)]
pub enum DepNodeKind {
  // Derived queries
  ParseFile = 0,
  ParseSchemas = 1,
  GetVaultConfig = 2,
  LowerNode = 3,
  FileSymbol = 4,
  Resolve = 5,
  BuiltinScope = 6,
  Members = 7,
  Scope = 8,
  ParentScope = 9,
  Referee = 10,
  Typecheck = 11,
  InferNodeType = 12,
  DeclaredNodeType = 13,
  ResolvedNodeType = 14,
  GetSymbolType = 15,
  EvaluateNode = 16,
  EvaluateResource = 17,
  EvaluateType = 18,
  GetTypeType = 19,
  GetObjectType = 20,
  GetBoolType = 21,
  GetStrType = 22,
  GetNumType = 23,
  GetListType = 24,
  GetDictType = 25,
  GetMathType = 26,
  GetDateTimeType = 27,
  GetDateType = 28,
  GetTimeType = 29,
  GetTrue = 30,
  GetFalse = 31,
  GetSchemaPropertyType = 32,
  GetSchemaType = 33,
  GetFuncType = 34,
  InstantiateType = 35,
  GetTypeTypeSymbol = 36,
  GetSchemaSymbol = 37,
  GetStrSymbol = 38,
  GetNumSymbol = 39,
  GetBoolSymbol = 40,
  GetDateSymbol = 41,
  GetDateTimeSymbol = 42,
  GetTimeSymbol = 43,
  GetMathSymbol = 44,
  GetListSymbol = 45,
  GetDictSymbol = 46,
  // Input structs
  File = 47,
  Project = 48,
}
